name: Fast Deploy Web App to Azure

on:
  push:
    branches:
      - feature/azure-deployment
      - main
  workflow_dispatch:

jobs:
  fast-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
